apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/social-group-marketing/backend_web:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_HOST
          value: mysql
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer  # Changed from ClusterIP to LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend