version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-here
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - backend-network
    command: >
      sh -c "chmod +x wait-for-db.sh && 
             ./wait-for-db.sh db 3306 python backend.py"

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=1

volumes:
  mysql_data:

networks:
  backend-network:
    name: backend-network
    driver: bridge